services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

volumes:
  dbdata:

networks:
  beaconx:
    external: true
